# Block requests with any extension
map $request_uri $is_blocked_extension {
    default 0;
    /robots.txt 0; # Allow robots.txt
    ~*^/static/ 0; # Allow anything under /static/
    ~*\.(.*)$ 1;
}

# Dynamic route mappings
map $request_uri $dynamic_route_target {
    default "";

    ~^/products/([a-f0-9]+)/?$ "/products/id.php";
}
map $request_uri $dynamic_route_query_params {
    default "";

    ~^/products/([a-f0-9]+)/?$ "id=$1";
}

map $uri $uri_no_slash {
    default $uri;
    ~^(.+)/$ $1;
}

server {
    listen 80;
    server_name localhost marketplace.ianbunag.dev _;
    root /var/www/html/public;
    absolute_redirect off;
    port_in_redirect on;

    if ($is_blocked_extension) {
        return 404;
    }

    # Block common scrapers and bots
    if ($http_user_agent ~* (Bytespider|AdsBot-Google|Amazonbot|anthropic-ai|applebot|AwarioBot|CCBot|ChatGPT-User|Claude-Web|ClaudeBot|CommonCrawl|DotBot|facebookexternalhit|GPTBot|HeadlessChrome|ImagesiftBot|magpie-crawler|MJ12bot|Omgilibot|PetalBot|Pinterestbot|SemrushBot|Sogou|YandexBot)) {
        return 403;
    }

    index index.php index.html;

    location /static/ {
        try_files $uri =404;
        log_not_found off;
        access_log off;
        expires max;
        add_header Cache-Control "public, no-transform";

        location ~* \.css$ {
            expires 1h;
            add_header Cache-Control "public, no-transform, must-revalidate";
            etag on;
        }
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
        expires max;
    }

    # Catch-all location for other requests
    location / {
        try_files $uri $uri/ @try_php_or_html;
    }

    location @try_php_or_html {
        # Handle dynamic routes
        if ($dynamic_route_target != "") {
            rewrite ^ $dynamic_route_target?$dynamic_route_query_params last;
        }

        # Check if .php version exists, otherwise try directory index
        if (-f $document_root$uri_no_slash.php) {
            rewrite ^ $uri_no_slash.php last;
        }

        if (-f $document_root$uri_no_slash/index.php) {
            rewrite ^ $uri_no_slash/index.php last;
        }

        try_files $uri_no_slash.html $uri_no_slash/index.html =404;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
